### PR TITLE
smb_docker for rss 2024

### PR DESCRIPTION
**Pull request by Huoleit**

### CODE REVIEW

**Comment by mantelt** [comment]
ready to merge?

**Comment by Huoleit** [comment]
> ready to merge?

Can you help to test on whatever platforms to see if you can launch the gazebo sim? I made a minor update. If it works, then it is ready to merge.

**Comment by mantelt** [comment]
> > ready to merge?
> 
> Can you help to test on whatever platforms to see if you can launch the gazebo sim? I made a minor update. If it works, then it is ready to merge.

seems to still work on Linux.

**Comment by Huoleit** [comment]
> > > ready to merge?
> > 
> > 
> > Can you help to test on whatever platforms to see if you can launch the gazebo sim? I made a minor update. If it works, then it is ready to merge.
> 
> docker with x11 forwarding seems to still work on Linux.

Yes. I mention that in doc. X11 forwarding is only supported on Linux. In Windows, you must install extra packages to translate x11 traffic to the format that Windows can understand.

**Comment by Huoleit** [comment]
I tested it on Mac. It works. After you finish the test, it should be ready to merge.

**Review by mantelt — APPROVED** [review]
didn't go through everything in detail.
seems to work nicely!

**Comment by Huoleit** [comment]
It should be fine. I didn't change anything important since Per helped to test.

**Comment by mantelt** [comment]
> > > > ready to merge?
> > > 
> > > 
> > > Can you help to test on whatever platforms to see if you can launch the gazebo sim? I made a minor update. If it works, then it is ready to merge.
> > 
> > 
> > docker with x11 forwarding seems to still work on Linux.
> 
> Yes. I mention that in doc. X11 forwarding is only supported on Linux. In Windows, you must install extra packages to translate x11 traffic to the format that Windows can understand.

I would have left that option in the docs (X11 forwarding on Windows). but the VNC solution seems to work as well. so that's ok.

**Pull request merged**
